### ISSUE TITLE
most of time is SLOWER than cargo

### ISSUE THREAD

**Issue by buf1024** [dimensionhq/fleet#21]
test project druid.

it's slower than cargo.

most of time after clean, cargo cause 38s the compile,

but fleet causes 45s, and sometimes more than 2min.

**Comment by VarunPotti** [comment]
Hey @buf1024, a few questions, 
- Your OS?
- Are you using WSL?
- What build/run command are you using?
- What are the contents of the file .cargo/config.toml?
- and your fleet version (`fleet --version`)
- Github link for the project

**Comment by CohenArthur** [comment]
Seconded - Same on my project
- OS: Linux, Archlinux distribution
- Not using WSL
- `fleet build` and `cargo build`
- `.cargo/config.toml`: After running fleet, but empty otherwise
```toml
[build]
rustc-wrapper = '/home/arthur/.cargo/bin/sccache'
[target.x86_64-unknown-linux-gnu]
rustflags = [
    '-Clink-arg=-fuse-ld=lld',
    '-Zshare-generics=y',
]
linker = '/usr/bin/clang'

[target.x86_64-pc-windows-msvc]
rustflags = ['-Zshare-generics=y']
linker = 'rust-lld.exe'

[target.x86_64-apple-darwin]
rustflags = [
    '-C',
    'link-arg=-fuse-ld=/usr/local/bin/zld',
    '-Zshare-generics=y',
    '-Csplit-debuginfo=unpacked',
]
[profile.dev]
opt-level = 0
debug = 2
incremental = true
codegen-units = 512

[profile.release]
opt-level = 3
debug = 0
incremental = false
codegen-units = 256
split-debuginfo = '...'
```
- `fleet --version`: `0.0.8`
- github link to the project: https://github.com/jinko-core/jinko
